steps:
# Uses the ubuntu build step:
# to run a shell script and set TAG
- name: 'ubuntu'
  args: ['bash', './.scripts/set_tag.sh']
  id: 'set_tag'

# build docker image
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    source TAG
    docker build \
      -t quay.io/rimusz/k8s-helm:latest \
      -t quay.io/rimusz/k8s-helm:$${HELM_TAG} .
  id: 'build_image'

# pull quay.io robot creds from bucket
- name: gcr.io/cloud-builders/gsutil
  args: ['cp', 'gs://rimusz-cloudbuilder/quay-io-creds/robot.creds', '/workspace/']
  id: 'fetch_robot_creds'
  waitFor:
  - 'build_image'

# push to quay.io
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    source /workspace/robot.creds
    docker login -u=$${QUSER} -p=$${PASSWORD} quay.io
    docker push quay.io/rimusz/k8s-helm
  id: push_image_quay_io
  waitFor:
  - 'fetch_robot_creds'
